import "./globals.css";

import { Inter, Merriweather } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], weight: ['400', '700'] });
const merriweather = Merriweather({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${inter.className} ${merriweather.className}`}>
        {children}
        </body>
        </html>
    );
}

